import pandas as pd
from typing import Dict, Any, List, Optional
from utils.domain_checkers import DomainIntelligence

class ReasoningGenerator:
    """
    Agent responsible for semantic understanding and schema design.
    Grounds LLM reasoning in industry standards like FHIR and Basel III.
    
    Academic Motivation: Reasoning allows the framework to understand 'Contextual 
    Integrity' (Nissenbaum, 2004), ensuring that synthesis doesn't just match 
    distributions but also respects the 'spirit' of the data domain.
    """
    
    def __init__(self):
        self.domain_checker = DomainIntelligence()

    async def process(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """
        Processes metadata to generate semantic logic and compliance constraints.
        
        Academic Motivation: Grounding LLM reasoning in domain ontologies 
        ensures semantic viability (Duan et al., 2022).
        """
        domain = state.get("domain", "Healthcare")
        df: Optional[pd.DataFrame] = state.get("raw_data")
        iteration = state.get("iteration", 0)
        feedback = state.get("judge_feedback", None)

        print(f"[ReasoningGenerator] generating policy-aware logic (Iter {iteration}). Domain: {domain}")

        if df is None:
            return state

        columns = df.columns.tolist()

        # 1. Semantic Grounding (New in Module 5)
        compliance_check = {}
        if domain == "Healthcare":
            compliance_check = self.domain_checker.check_fhir_alignment(columns)
        elif domain == "Finance":
            compliance_check = self.domain_checker.check_basel_compliance(columns)
        else:
            compliance_check = {"is_aligned": True, "standard": "General"}

        # 2. Simulated CoT / Reasoning Trace
        # In a real system, this would be generated by a LLM.
        trace = f"Analyzed {len(columns)} fields for {domain} synthesis. "
        
        if compliance_check.get("is_aligned") or compliance_check.get("is_compliant"):
            trace += f"Validated against {compliance_check.get('standard')}. "
        else:
            trace += "WARNING: Domain standards alignment issues detected. "

        if feedback and iteration > 0:
            trace += f"[Refined by Feedback: {feedback}]"

        # 3. Decision Skeleton
        schema_skeleton = {
            "fields": columns,
            "domain_constraints": compliance_check,
            "synthesis_strategy": "Iterative-Adversarial" if domain != "Finance" else "Temporal-GAN"
        }

        # Update State
        state["reasoning_trace"] = trace
        state["compliance_check"] = compliance_check
        state["schema_skeleton"] = schema_skeleton
        
        return state
